### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by mzwaal** [justinbangerter/gdscript-repl#1]
Hi,

Trying to use the plugin. I get this when adding it to my project:

  res://addons/repl/repl_env.gd:339 - Parse Error: Identifier "GodotPhysicsServer3D" not declared in the current scope.
  res://addons/repl/repl_env.gd:339 - Parse Error: Identifier "GodotPhysicsServer3D" not declared in the current scope.
  res://addons/repl/repl_parser.gd:-1 - Compile Error: 
  res://addons/repl/control.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/repl/control.gd" with error "Compilation failed". (User)
  res://addons/repl/control.gd:7 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
  
Running on Godot Engine v4.2.2.stable.mono.official

And installing it via the AssetLib on 4th July 2024

**Comment by justinbangerter** [comment]
Hey, thanks for letting me know.

I'm guessing you don't have some Physics 3D classes loaded.

I found a way to dynamically load classes from the base environment into the REPL environment. So, this should go away after the next release (just submitted to the asset lib).

Let me know if it resolves the issue for you.

**Comment by mzwaal** [comment]
It is working, thanks!
